// apps/angular/demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { CopilotKitConfigDirective, CopilotChatComponent } from '@copilotkit/angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CopilotKitConfigDirective, CopilotChatComponent],
  template: `
    <div
      style="height: 100vh; margin: 0; padding: 0; overflow: hidden;"
      copilotkitConfig
      [runtimeUrl]="runtimeUrl"
    >
      <copilot-chat [threadId]="'xyz'"></copilot-chat>
    </div>
  `,
})
export class AppComponent {
  runtimeUrl = 'http://localhost:3001/api/copilotkit';
}

// apps/demo/src/app/page.tsx
"use client";

import { CopilotChat, CopilotKitProvider } from "@copilotkit/react";

// Disable static optimization for this page
export const dynamic = "force-dynamic";

export default function Home() {
  return (
    <CopilotKitProvider runtimeUrl="/api/copilotkit">
      <div
        style={{ height: "100vh", margin: 0, padding: 0, overflow: "hidden" }}
      >
        <CopilotChat threadId="1" />
      </div>
    </CopilotKitProvider>
  );
}
